name: Maven Workflow

on:
  workflow_call:
jobs:
  setup-build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: checkout-source
        uses: actions/checkout@v3
      - name: upload-artifacts
        uses: actions/upload-artifact@v1
        with:
          name: working-dir
          path: ${{ github.workspace }}

  package-artifacts:
    runs-on: [ ubuntu-latest ]
    needs: package-artifacts
    steps:
      - name: download-artifacts
        uses: actions/download-artifact@v1
        with:
          name: working-dir
          path: ${{ github.workspace }}
      - name: build-container
        run: podman build -t ${{ github.repository }}:${{ github.sha }} .
      - name: upload-artifacts
        uses: actions/upload-artifact@v1
        with:
          name: working-dir
          path: ${{ github.workspace }}