name: Maven Workflow

on:
  workflow_call:
jobs:
  setup:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: setup-app-clone
        uses: actions/checkout@v3
      - name: upload-artifacts
        uses: actions/upload-artifact@v1
        with:
          name: working-dir
          path: ${{ github.workspace }}

  build:
    runs-on: [ ubuntu-latest ]
    needs: setup
    steps:
      - name: download-artifacts
        uses: actions/download-artifact@v1
        with:
          name: working-dir
          path: ${{ github.workspace }}
      - name: build-artifacts
        run: |
          mvn clean 
          mvn test
          mvn package
      - name: upload-artifacts
        uses: actions/upload-artifact@v1
        with:
          name: working-dir
          path: ${{ github.workspace }}

  containerize:
    runs-on: [ ubuntu-latest ]
    needs: setup
    steps:
      - name: download-artifacts
        uses: actions/download-artifact@v1
        with:
          name: working-dir
          path: ${{ github.workspace }}
      - name: build-container
        run: |
          podman info
      - name: upload-artifacts
        uses: actions/upload-artifact@v1
        with:
          name: working-dir
          path: ${{ github.workspace }}