name: Maven Workflow

on:
  workflow_call:
jobs:
  setup:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: checkout-source
        uses: actions/checkout@v3
      - name: upload-artifacts
        uses: actions/upload-artifact@v1
        with:
          name: working-dir
          path: ${{ github.workspace }}

  build:
    runs-on: [ ubuntu-latest ]
    needs: setup
    steps:
      - name: download-artifacts
        uses: actions/download-artifact@v1
        with:
          name: working-dir
          path: ${{ github.workspace }}
      - name: podman-login
        run: podman login -u="${{ secrets.PODMAN_USERNAME }}" -p="${{ secrets.PODMAN_PASSWORD }}" ${{ secrets.REPO_HOSTNAME }}
      - name: podman-build
        run: podman build -t REPO_USERNAME}}/${{ github.event.repository.name }}:${{ github.sha }} .
      - name: podman-push
        run: podman push ${{ secrets.REPO_USERNAME }}/${{ github.event.repository.name }}:${{ github.sha }}
      - name: upload-artifacts
        uses: actions/upload-artifact@v1
        with:
          name: working-dir
          path: ${{ github.workspace }}