#  | secret|
#   | PODMAN_USERNAME |
#   | PODMAN_PASSWORD }}" ${{ secrets.REPO_HOSTNAME }}
#      - name: podman-build
#        run: podman build -t ${{ github.event.repository.name }}:${{ github.sha }} -f Containerfile
#      - name: podman-tag
#        run: podman tag ${{ github.event.repository.name }} ${{ secrets.REPO_HOSTNAME }}/${{ secrets.REPO_USERNAME }}/${{ github.event.repository.name }}:${{ github.sha }}
#      - name: podman-push
#        run: podman push ${{ secrets.REPO_HOSTNAME }}/${{ secrets.REPO_USERNAME }}/${{ github.event.repository.name }}:${{ github.sha }}

name: Maven Workflow
on:
  workflow_call:
    inputs:
      podman_username:
        required: false
        default: ${{ secrets.PODMAN_USERNAME }}
        type: string
jobs:
  setup:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: checkout-source
        uses: actions/checkout@v3
      - name: upload-artifacts
        uses: actions/upload-artifact@v1
        with:
          name: working-dir
          path: ${{ github.workspace }}

  containerize:
    runs-on: [ ubuntu-latest ]
    needs: setup
    steps:
      - name: download-artifacts
        uses: actions/download-artifact@v1
        with:
          name: working-dir
          path: ${{ github.workspace }}
      - name: podman-login
        run: podman login -u="${{ inputs.PODMAN_USERNAME }}" -p="${{ secrets.PODMAN_PASSWORD }}" ${{ secrets.REPO_HOSTNAME }}
      - name: podman-build
        run: podman build -t ${{ github.event.repository.name }}:${{ github.sha }} -f Containerfile
      - name: podman-tag
        run: podman tag ${{ github.event.repository.name }} ${{ secrets.REPO_HOSTNAME }}/${{ secrets.REPO_USERNAME }}/${{ github.event.repository.name }}:${{ github.sha }}
      - name: podman-push
        run: podman push ${{ secrets.REPO_HOSTNAME }}/${{ secrets.REPO_USERNAME }}/${{ github.event.repository.name }}:${{ github.sha }}
      - name: upload-artifacts
        uses: actions/upload-artifact@v1
        with:
          name: working-dir
          path: ${{ github.workspace }}