name: Maven Workflow

on:
  workflow_call:
jobs:
  setup:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: setup-app-clone
        uses: actions/checkout@v3

      - name: upload-artifacts
        uses: actions/upload-artifact@v1
        with:
          name: working-dir
          path: ${{ github.workspace }}